### ISSUE TITLE
Using requests with an async library is a bad idea.

### ISSUE THREAD

**Issue by applebee1558** [QuentinVezzani/NitroSniper#11]
You should use an async library like aiohttp, or just use discord.py’s internal http library to make the request. Using a sync library with an async library is a bad idea. The other way to do it is to just not use discord.py and just connect to the gateway manually.

**Comment by Vedza** [comment]
Thanks for teaching me that! I will update it when I have time to do it. It might be in a few weeks so if someone wants to do it, he can do a pull request and I'll accept it.

**Comment by ImAboutTo** [comment]
> You should use an async library like aiohttp, or just use discord.py’s internal http library to make the request. Using a sync library with an async library is a bad idea. The other way to do it is to just not use discord.py and just connect to the gateway manually.

Can you tell me why would this be a bad Idea?  Beacuse I used it in my bot to should I change it to for example https://ptb.discordapp.com/api/v6/entitlements/gift-codes/' or what do you mean ?

**Comment by ImAboutTo** [comment]
Btw I would add If the author is a bot check so that it wont react on a user typing **Giveaway** in the chat like message.auther.bot and...

**Comment by applebee1558** [comment]
@ImAboutTo no, I mean you should use another library like aiohttp as requests is sync/blocking, which would block your bot from receiving processing anything until the request completes since discord.py is async. It would also be better if a user-agent is sent that mimics the client to make detection harder

**Comment by ImAboutTo** [comment]
> @ImAboutTo no, I mean you should use another library like aiohttp as requests is sync/blocking, which would block your bot from receiving processing anything until the request completes since discord.py is async. It would also be better if a user-agent is sent that mimics the client to make detection harder

Thank you for your Tip, btw can I message u somewhere like discord or smth

**Comment by applebee1558** [comment]
You can join my server at: https://discord.gg/uCtymGD
Note: I don’t use not use nor do I endorce using this tool to all discord staff looking at this comment. Infact I even ban people in my server using this took through sending gift links to my game and checking entitlements/making my bot send an embed with giveaway, and seeing people react to it.

**Comment by ghost** [comment]
> You can join my server at: https://discord.gg/uCtymGD
> Note: I don’t use not use nor do I endorce using this tool to all discord staff looking at this comment. Infact I even ban people in my server using this took through sending gift links to my game and checking entitlements/making my bot send an embed with giveaway, and seeing people react to it.

Good prank

**Comment by Vedza** [comment]
Updated here bf3acbb0a5ce456b57b8bc5877c06a6dbd153806 (this doesn't mean that you should use this version, go use [NitroSniperGo](https://github.com/Vedzaa/NitroSniperGo) instead)
