### ISSUE TITLE
hi everyone

### ISSUE THREAD

**Issue by Tomi-boop** [QuentinVezzani/NitroSniper#16]
i dont understand how the program works and how to use it. Can someone explain it or help me?
Thanks, Tomi

**Comment by Vedza** [comment]
Hi, my program will claim every gift sent in discord servers you're on as well as join giveaways. So you need to get your token first (there is a link in the readme) and then install python3, pip, and the dependencies (pip install... commands in command prompt). You finally be able to run the program sniper.py ! If this seems easy for you, you will also be able to use my other version NitroSniperGo which is faster and as easy to install as this one.

**Comment by Tomi-boop** [comment]
> Hi, my program will claim every gift sent in discord servers you're on as well as join giveaways. So you need to get your token first (there is a link in the readme) and then install python3, pip, and the dependencies (pip install... commands in command prompt). You finally be able to run the program sniper.py ! If this seems easy for you, you will also be able to use my other version NitroSniperGo which is faster and as easy to install as this one.

ok, i installed python3, but i dont know how to install pip and dependencies, so when i run sniper.py, it just opens and closes, why?

**Comment by Vedza** [comment]
Give me your discord and I'll help you

**Comment by Tomi-boop** [comment]
can u give me urs cuz i have some sort of stars in my name

**Comment by Tomi-boop** [comment]
one sec

**Comment by Vedza** [comment]
You can copy it by clicking on your name on discord and paste it here

**Comment by Tomi-boop** [comment]
ye ik

**Comment by Tomi-boop** [comment]
my discord wont load -_-

**Comment by Tomi-boop** [comment]
✯ 𝑻𝒐𝒎𝒊 ✯
#4827

**Comment by Tomi-boop** [comment]
here
