### ISSUE TITLE
I have a Question

### ISSUE THREAD

**Issue by PeterStrick** [QuentinVezzani/NitroSniper#17]
Hello! I recently worked on a project called [NitroSniperGUI](https://github.com/PeterStrick/NitroSniperGUI) which allows you to easily run, manage, update, use and configure the Nitro Snipers.

Currently I include your Go and Python Nitro Snipers and the following Nitro Sniper, as well as credited you and linked your Nitro Snipers:
https://github.com/Melonai/rust-nitro-sniper/

So, I am here to ask if it is ok with you, for me to bundle your Nitro Sniper, or if you want me to stop bundling your Nitro Snipers.

Thanks!

Peter Strick

**Comment by Vedza** [comment]
Hi ! 
You should definitely use git submodule to keep them up to date, and I highly recommend to not run multiple bots at the same time.
But if you think this is useful I'm OK with it !

**Comment by PeterStrick** [comment]
Thanks!

**Comment by Vedza** [comment]
No problem, thanks for asking !

**Comment by PeterStrick** [comment]
> Hi !
> You should definitely use git submodule to keep them up to date, and I highly recommend to not run multiple bots at the same time.
> But if you think this is useful, I'm OK with it!

Your idea of using submodules is good, but not useful as I am compiling the .py and .go files into a windows executable so that the end user doesn't have to install Python and the Go Programming Language for the Nitro Snipers to work.
Just compiling and updating the Snipers manually is easier, because I get notified as well when a new change was made to the Sniper, so that I can update my Nitro Sniper GUI with the new Nitro Sniper.

**Comment by Vedza** [comment]
Oh ok I understand
