### ISSUE TITLE
doesnt work on dm's

### ISSUE THREAD

**Issue by enescaglayan** [QuentinVezzani/NitroSniper#2]
because when you do ctx.guild private messages doesnt have guilds then it errors i fixed it on my own but you should fix it

**Comment by Zalatis** [comment]
Just make a pull request with your fix and he will push it :)

**Comment by QuentinVezzani** [comment]
I fixed it 4e7bb616f718c012af5c0f17785bd88e350ec8de but next time do a pull request please !
BTW, If you don't care about the giveaway joiner I made a Go version a bit faster than this one here: https://github.com/QuentinVezzani/NitroSniperGo
