### ISSUE TITLE
can you make it to not join some giveaway?

### ISSUE THREAD

**Issue by snipers-lab** [QuentinVezzani/NitroSniper#22]
Not To Join Some GiveAway Has **Do Not Join**

There are some fake giveaways to find auto reactors

**Comment by Vedza** [comment]
Use my Go version, it's faster and only join Nitro giveaways

**Comment by snipers-lab** [comment]
I'm using Go version also but I want to join other giveaways  that's why I'm using this version too .plz help me How can I stop it from joining fake giveaways keyword "Don't , Do Not"

**Comment by ImAboutTo** [comment]
Just add a bot or not check

**Comment by Vedza** [comment]
I don't have time to do this now but you can do a pull request

**Comment by snipers-lab** [comment]
or help me where should i edit to obtain that ?

**Comment by Vedza** [comment]
line 95

**Comment by snipers-lab** [comment]
do you use discord ?

**Comment by Vedza** [comment]
No I don't

**Comment by snipers-lab** [comment]
If you can please help me

**Comment by snipers-lab** [comment]
just make the bot not to enter such giveaways with keyword "BAN,DON'T,DO NOT,AUTO REACT"
