### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by SloppyPuppy** [QuentinVezzani/NitroSniper#23]
http://prntscr.com/ui3bpm

**Comment by Vedza** [comment]
Hi, make sure your library is up to date. Or check if your token is good.

**Comment by SloppyPuppy** [comment]
Yea my fault, ty for the very quick reply! It was the token, I am not particularly versed in python but that error does mean there is a token missing. Also it says it claimed multiple gifts by now, some (already claimed) some supposedly claimed by my account, but none have actually been claimed. I still don't have any discord nitro (22:17:51 [-] Sniped code: SfYGbTwkqzuUVuMpz2n9zaRG From El putino#5199 [beetards > chat-l]
 Delay: 0.382s)
I have added 2fa since before and still won't claim a single code, does this program just snipe codes and outputs them, or does it also claim them, do I need to write something separate to redeem them?

**Comment by Vedza** [comment]
It prints "code applied" when you get a nitro, but you should use the other Go version which is faster so you will have more chance to get Nitro
