### ISSUE TITLE
help

### ISSUE THREAD

**Issue by whislol** [QuentinVezzani/NitroSniper#24]
it insta closes python, what do i need to be able to open it

**Comment by Vedza** [comment]
check traceback.txt pls

**Comment by whislol** [comment]
im so new to "coding" and all where do i do that?

**Comment by Vedza** [comment]
You should have a new file named traceback in the directory

**Comment by whislol** [comment]
in the file i downloaded i see token.json sniper.py a screenshot license and gitignore

**Comment by Vedza** [comment]
You either didn't install dependencies or your token is not working or in the wrong place, but you should use NitroSniperGo which is a faster sniper than this one and you can get compiled version [here](https://github.com/Vedzaa/NitroSniperGo/releases).
You need to put your token {"token": "HERE"}
