### ISSUE TITLE
Starting error?

### ISSUE THREAD

**Issue by juanjoayala01** [QuentinVezzani/NitroSniper#25]
Hello, I put the user token into the json file and run the sniper.py, but the program get stuck in the red letters, it doesent move nor show any error after that. Could you help me, please?

**Comment by Vedza** [comment]
Hi, It might come from Windows terminal waiting for a text input even if there is not one needed but you should use my other sniper NitroSniperGo which is faster. If you really want to use this one (even if it makes no sense), send me your discord, and we'll figure this out.
