### ISSUE TITLE
How do I use .py files?

### ISSUE THREAD

**Issue by henryglends** [QuentinVezzani/NitroSniper#26]
Sorry, I’ve never used a python file before. What do I do to open it?

**Comment by PeterStrick** [comment]
For .py files (Python Files) you either install python, or compile it yourself.

@henryglends You can use my project though, which simplifies the process of configuring and getting Nitro Snipers up and running.
https://github.com/PeterStrick/NitroSniperGUI
It´s free of charge, very easy to install and includes 3 different Nitro Snipers, including this one.
