### ISSUE TITLE
Redeclaration of main

### ISSUE THREAD

**Issue by Spinicle** [QuentinVezzani/NitroSniper#30]
Whenever i run sniper.go, i get the error that main has been redeclared.
![image](https://user-images.githubusercontent.com/70312979/103725334-55840380-4ffc-11eb-8faa-43fe0324dcfa.png)

**Comment by Vedza** [comment]
This is the python sniper repo. it should work with :
```
 go mod download
 go build
 ./NitroSniperGo

```

**Comment by Spinicle** [comment]
Oof, yeah sorry meant to open it in the Go version, the new sniper you made.

**Comment by Vedza** [comment]
Np, if it still doesn't work you can send me your discord here, and I'll try to help you

**Comment by Spinicle** [comment]
It isn't, my discord is Spinicle#0001
