### ISSUE TITLE
nitro isn't going into my account

### ISSUE THREAD

**Issue by Tasnemo** [QuentinVezzani/NitroSniper#31]
The program is saying they sniped the code, but it doesn't say I got nitro.

**Comment by Vedza** [comment]
What did it say after that ?

**Comment by Tasnemo** [comment]
It said this 15:32:07 [-] Sniped code: zNrCWxyNVXJtgWbG From ! " Pαr†y#9999 [Popular Giveaways > 🎁・quick・drop]
 Delay: 0.128s

Then I hear someone redeemed it later

**Comment by Vedza** [comment]
OK, It's probably an update from discord that this sniper doesn't handle. But you should use my other sniper https://github.com/Vedza/NitroSniperGo which is faster and have more feature
