### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by JacobWoolbright** [QuentinVezzani/NitroSniper#5]
Looking over the code I saw it to be standard asyncio discord.py, I made a bot user and it gives me "discord.errors.LoginFailure: Improper token has been passed". Where do I get this token from if not a bot user?

**Comment by Vedza** [comment]
Hi, 
You should look here :
Https://github.com/Tyrrrz/DiscordChatExporter/wiki/Obtaining-Token-and-Channel-IDs
or
https://greasyfork.org/en/scripts/395741-get-discord-token

**Comment by JacobWoolbright** [comment]
Thanks, I figured it out, any chance you could include that inside the readme?

**Comment by Vedza** [comment]
It's added! 920df8a890ed8ab8e38ccae6daf62f1a69b8364f
