### ISSUE TITLE
No module named 'discord'

### ISSUE THREAD

**Issue by Waliers** [QuentinVezzani/NitroSniper#6]
Whenever I run sniper.py I get the folowing error;

NitroSniper-master>sniper.py
Traceback (most recent call last):
  File "D:\Downloads\NitroSniper-master\NitroSniper-master\sniper.py", line 7, in <module>
    from discord.ext import commands
ModuleNotFoundError: No module named 'discord'

**Comment by Vedza** [comment]
```
pip install discord.py colorama requests
```

**Comment by enescaglayan** [comment]
You shouldnt use selfbot if you dont know this
