### ISSUE TITLE
[Issue] Auto-Detect fake code

### ISSUE THREAD

**Issue by Zalatis** [QuentinVezzani/NitroSniper#7]
Looks like the latest update with regex make all "discord.gift/" link are detected as fake code even if they are real 
![83243240-eb6dcb00-a19d-11ea-8b2d-bcef34736aba](https://user-images.githubusercontent.com/16846453/83301211-8778f000-a1f9-11ea-9728-7ec2ef3da88d.png)

**Comment by Ninjaex13** [comment]
yea its happening to me too

**Comment by Vedza** [comment]
I fixed it fd746897803842de45a9281c9d01d64c9967a6e1, Sorry ! But you should definitely used [this Go version](https://github.com/QuentinVezzani/NitroSniperGo) if you didn't get free nitro with this one.
